### ISSUE TITLE
请问如何添加背景音乐呢？

### ISSUE THREAD

**Issue by JackyYuenDacai** [bookzhan/bzmedia#1]
请问如何添加背景音乐呢？
ffmpeg能添加自己编译出来的库来支持x86吗

**Comment by bookzhan** [comment]
我整理一下把这一块开源出来，x86的库你可以自己编译，详细请参考https://www.bzblog.online/wordpress/index.php/2020/05/26/ffmpeg-build-android/

**Comment by bookzhan** [comment]
@JackyYuenDacai  添加背景音乐的代码已经放出来了

**Comment by JackyYuenDacai** [comment]
添加音乐是用命令的吗

**Comment by bookzhan** [comment]
> 添加音乐是用命令的吗

是的，最底层是用的命令，详情请看这里https://www.raoyunsoft.com/wordpress/index.php/2020/07/24/addbgmusic/
