### ISSUE TITLE
请问如何调整比例？

### ISSUE THREAD

**Issue by Besame521** [bookzhan/bzmedia#2]
以下是我调整比例的代码，发现需要调用两次才能重置视频预览。
请大佬指点一下。感谢！
bz_camera2_view.setPreviewTargetSize(480, 480);
ViewGroup.LayoutParams params = bz_camera2_view.getLayoutParams();
params.height = ScreenUtils.getWidthPixels(RecordActivity.this);
bz_camera2_view.setLayoutParams(params);
bz_camera2_view.startPreview();

**Comment by bookzhan** [comment]
Camera的分辨率是有限的几种，建议采用遮罩+裁剪YUV的方式，YUV裁剪可以参考这个去做https://www.raoyunsoft.com/wordpress/index.php/2020/05/25/androidlibyuv/
