### ISSUE TITLE
录制视频支持断点录制么，不能暂停

### ISSUE THREAD

**Issue by lmJojo** [bookzhan/bzmedia#3]

**Comment by bookzhan** [comment]
录制完成后可以把几段视频合并在一起的，我国庆的时候把这个方法传上来

**Comment by bookzhan** [comment]
@lmdeng 好了通过这个方法可以实现断点录制,不过要保证视频宽高一样,编码器一样
![image](https://user-images.githubusercontent.com/11169519/135590885-3b0e2d19-89b4-4e84-bef5-fbbb33ca149a.png)

**Comment by lmJojo** [comment]
感谢感谢
