### ISSUE TITLE
demo 的Record4Camera1 预览中灭屏几次就会卡死，

### ISSUE THREAD

**Issue by lmJojo** [bookzhan/bzmedia#4]
![image](https://user-images.githubusercontent.com/53633231/137124054-ef3b3e56-6046-433d-8ce8-62081ccd99ae.png)

**Comment by lmJojo** [comment]
![image](https://user-images.githubusercontent.com/53633231/137124455-fe42ddc7-2eb2-4d98-bdb6-754d205b4359.png)

**Comment by bookzhan** [comment]
是bzcamera库的问题,我已经更新了
