### ISSUE TITLE
预览旋转90度

### ISSUE THREAD

**Issue by joklmT** [bookzhan/bzmedia#5]
横屏下手动调用 switchCamera2ID( ) 后预览旋转了90度, 设置旋转90度 也只是预览角度正常，两侧空白的，录制结果还是旋转了90度，该怎么调整呢，Camera 实例貌似也没有api 接口获取

 bz_camera_view.switchCamera2ID(getCameraId());
 bz_camera_view.setRotation(90f);

**Comment by bookzhan** [comment]
![搜狗截图20211024174955](https://user-images.githubusercontent.com/11169519/138588931-46313238-c49f-4d2d-9747-c0689160b787.png)
这个函数第三个参数是控制翻转的,最后一个参数是控制旋转角度,你可以根据设备进行调整, 但是你需要注意录制视频的时候传的宽高要调换
